//This file will contain the logic to turn each resource type into a string of 
// Terraform code.
//from my analysis what we are doing is that we are :
//1. Looping through all the resources in our blueprint (state)
//2. For each resource, we check its type and generate the corresponding HCL code using a switch statement
//3. We handle specific properties for each resource type (like engine, storageGb for RDS) and also include any parent-child relationships (like VPC associations)
//4. Finally, we concatenate all the generated HCL code into a single string that represents the entire infrastructure as code configuration.
// generators/hcl-generator/formatter.ts

import { InfrastructureState, AWSResource } from '../../core/ast-types';

export function generateTerraform(state: InfrastructureState): string {
  let hcl = `
# Generated by React2AWS
# Provider Configuration
provider "aws" {
  region = "us-east-1"
}`;

  // Loop through every resource in our blueprint
  for (const id in state.resources) {
    const resource = state.resources[id];
    hcl += renderResource(resource);
 }

  return hcl;
}

function renderResource(res: AWSResource): string {
  switch (res.type) {
    case 'VPC':
      return `
        resource "aws_vpc" "${res.id}" {
          cidr_block           = "${res.cidrBlock || '10.0.0.0/16'}"
          enable_dns_support   = true
          enable_dns_hostnames = true
          tags = {
            Name = "${res.id}"
          }
        }
        `;

case 'RDS':
      return `
        resource "aws_db_instance" "${res.id}" {
          identifier        = "${res.id}"
          engine            = "${res.engine || 'postgres'}"
          instance_class    = "${res.instanceClass || 'db.t3.micro'}"
          allocated_storage = ${res.storageGb || 20}
          multi_az          = ${res.multiAz || false}
          skip_final_snapshot = true
          
          # Link to VPC if parent exists
          ${res.parent ? `# Associated with VPC: ${res.parent}` : ''}
        }
        `;

case 'EC2':
    return `
    resource "aws_instance" "${res.id}" {
        ami = "${res.amiId || 'ami-0c02fb55956c7d316'}"
        instance_type = "${res.instanceType || 't2.micro'}"
        key_name = "${res.keyName || 'my-key-pair'}"
        security_groups = [${res.securityGroupIds ? res.securityGroupIds.map(sg => `"${sg}"`).join(', ') : ''}]
        tags = {
            Name = "${res.id}"
        }
    }
    `;

case 'S3':
    return `
    resource "aws_s3_bucket" "${res.id}" {
        bucket = "${res.bucketName || res.id}"
        versioning {
            enabled = ${res.versioningEnabled || false}
        }
        acl = "${res.accessControl || 'private'}"
        tags = {
            Name = "${res.id}"
        }
    }
    `;

case 'Lambda':
    return `
    resource "aws_lambda_function" "${res.id}" {
        function_name = "${res.id}"
        runtime = "${res.runtime || 'nodejs14.x'}"
        handler = "${res.handler || 'index.handler'}"
        code_size = ${res.codeSizeMb ? res.codeSizeMb * 1024 * 1024 : 52428800} # Convert MB to Bytes
        timeout = ${res.timeoutSec || 30}
        tags = {
            Name = "${res.id}"
        }
    }
    `;
    default:
      return `\n# Resource type ${(res as any).type} not yet implemented in generator\n`;
}
}


