// formatter.ts
import { InfrastructureState, AWSResource } from '../../core/schema/ast-types';

export function generateTerraform(state: InfrastructureState): string {
  let hcl = `
# Generated by React2AWS
# Provider Configuration
provider "aws" {
  region = "us-east-1"
}`;

  for (const id in state.resources) {
    const resource = state.resources[id];
    hcl += renderResource(resource);
  }

  return hcl;
}

function renderResource(res: AWSResource): string {
  switch (res.type) {
    case 'VPC':
      return `
        resource "aws_vpc" "${res.id}" {
          cidr_block           = "${res.cidrBlock || '10.0.0.0/16'}"
          enable_dns_support   = true
          enable_dns_hostnames = true
          tags = {
            Name = "${res.id}"
          }
        }
        `;

    case 'RDS':
      return `
        resource "aws_db_instance" "${res.id}" {
          identifier        = "${res.id}"
          engine            = "${res.engine || 'postgres'}"
          instance_class    = "${res.instanceClass || 'db.t3.micro'}"
          allocated_storage = ${res.storageGb || 20}
          multi_az          = ${res.multiAz || false}
          skip_final_snapshot = true
          
          # Link to VPC if parent exists
          ${res.parent ? `# Associated with VPC: ${res.parent}` : ''}
        }
        `;

    case 'EC2':
      return `
    resource "aws_instance" "${res.id}" {
        ami = "${res.amiId || 'ami-0c02fb55956c7d316'}"
        instance_type = "${res.instanceType || 't2.micro'}"
        key_name = "${res.keyName || 'my-key-pair'}"
        security_groups = [${res.securityGroupIds ? res.securityGroupIds.map(sg => `"${sg}"`).join(', ') : ''}]
        tags = {
            Name = "${res.id}"
        }
    }
    `;

    case 'S3':
      return `
resource "aws_s3_bucket" "${res.id}" {
  bucket = "${res.bucketName || res.id}"
  tags = {
    Name = "${res.id}"
    Environment = "Production"
  }
}

# AUTOMATED SECURITY: Enforce AES256 Encryption
resource "aws_s3_bucket_server_side_encryption_configuration" "${res.id}_encryption" {
  bucket = aws_s3_bucket.${res.id}.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

# AUTOMATED SECURITY: Block Public Access
resource "aws_s3_bucket_public_access_block" "${res.id}_access" {
  bucket                  = aws_s3_bucket.${res.id}.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# AUTOMATED IAM: Principle of Least Privilege
resource "aws_iam_role" "${res.id}_access_role" {
  name = "${res.id}-read-only-role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = { Service = "ec2.amazonaws.com" }
    }]
  })
}
`;
    case 'Lambda':
      return `
    resource "aws_lambda_function" "${res.id}" {
        function_name = "${res.id}"
        runtime = "${res.runtime || 'nodejs14.x'}"
        handler = "${res.handler || 'index.handler'}"
        code_size = ${res.codeSizeMb ? res.codeSizeMb * 1024 * 1024 : 52428800} # Convert MB to Bytes
        timeout = ${res.timeoutSec || 30}
        tags = {
            Name = "${res.id}"
        }
    }
    `;
    case 'Subnet':
      return `
resource "aws_subnet" "${res.id}" {
  vpc_id                  = ${res.parent ? `aws_vpc.${res.parent}.id` : 'var.vpc_id'}
  cidr_block              = "${res.cidrBlock || '10.0.1.0/24'}"
  availability_zone       = "${res.availabilityZone || 'us-east-1a'}"
  map_public_ip_on_launch = ${res.mapPublicIpOnLaunch || false}
  tags = {
    Name = "${res.id}"
  }
}
`;

    case 'SecurityGroup':
      const ports = res.ingressPorts || [80, 443];
      const ingressRules = ports.map(port => `
  ingress {
    from_port   = ${port}
    to_port     = ${port}
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }`).join('');

      return `
resource "aws_security_group" "${res.id}" {
  name        = "${res.id}"
  description = "${res.description || 'Managed by CloudAST'}"
  vpc_id      = ${res.parent ? `aws_vpc.${res.parent}.id` : 'var.vpc_id'}
${ingressRules}
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}
`;

    case 'DynamoDB':
      return `
resource "aws_dynamodb_table" "${res.id}" {
  name           = "${res.id}"
  billing_mode   = "${res.billingMode || 'PAY_PER_REQUEST'}"
  hash_key       = "${res.hashKey || 'id'}"

  attribute {
    name = "${res.hashKey || 'id'}"
    type = "S"
  }
  
  tags = {
    Environment = "Production"
  }
}
`;

    case 'APIGateway':
      return `
resource "aws_apigatewayv2_api" "${res.id}" {
  name          = "${res.id}-api"
  protocol_type = "${res.protocolType || 'HTTP'}"
}

${res.targetLambda ? `
resource "aws_apigatewayv2_integration" "${res.id}_integration" {
  api_id           = aws_apigatewayv2_api.${res.id}.id
  integration_type = "AWS_PROXY"
  integration_uri  = aws_lambda_function.${res.targetLambda}.invoke_arn
}

resource "aws_lambda_permission" "${res.id}_api_gw" {
  statement_id  = "AllowExecutionFromAPIGateway"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.${res.targetLambda}.function_name
  principal     = "apigateway.amazonaws.com"
  source_arn    = "\${aws_apigatewayv2_api.${res.id}.execution_arn}/*/*"
}
` : ''}
`;

    case 'GlueCatalog':
      return `
resource "aws_glue_catalog_database" "${res.id}" {
  name = "${(res as any).databaseName || res.id}"
}
`;

    case 'GlueCrawler':
      return `
# AUTOMATED IAM: Role for Glue Crawler to read S3 and write to Catalog
resource "aws_iam_role" "${res.id}_role" {
  name = "${res.id}-crawler-role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = { Service = "glue.amazonaws.com" }
    }]
  })
}

resource "aws_iam_role_policy_attachment" "${res.id}_glue_service" {
  role       = aws_iam_role.${res.id}_role.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole"
}

resource "aws_iam_policy" "${res.id}_s3_policy" {
  name = "${res.id}-s3-policy"
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Action = ["s3:GetObject", "s3:PutObject", "s3:ListBucket"]
      Resource = ["\${aws_s3_bucket.${(res as any).targetBucket}.arn}", "\${aws_s3_bucket.${(res as any).targetBucket}.arn}/*"]
    }]
  })
}

resource "aws_iam_role_policy_attachment" "${res.id}_s3_attach" {
  role       = aws_iam_role.${res.id}_role.name
  policy_arn = aws_iam_policy.${res.id}_s3_policy.arn
}

resource "aws_glue_crawler" "${res.id}" {
  database_name = aws_glue_catalog_database.${(res as any).targetCatalogId}.name
  name          = "${res.id}"
  role          = aws_iam_role.${res.id}_role.arn
  ${(res as any).scheduleCron ? `schedule = "${(res as any).scheduleCron}"` : ''}

  s3_target {
    path = "s3://\${aws_s3_bucket.${(res as any).targetBucket}.bucket}/"
  }
}
`;

    case 'Athena':
      return `
resource "aws_athena_workgroup" "${res.id}" {
  name = "${res.id}-workgroup"

  configuration {
    enforce_workgroup_configuration    = true
    publish_cloudwatch_metrics_enabled = true

    result_configuration {
      output_location = "s3://\${aws_s3_bucket.${(res as any).outputBucket}.bucket}/query-results/"
      
      encryption_configuration {
        encryption_option = "SSE_S3"
      }
    }
  }
}
`;

    default:
      return `\n# Resource type ${(res as any).type} not yet implemented in generator\n`;
  }
}