import { InfrastructureState } from '../../../../core/schema/ast-types';

export function generateCloudFormation(state: InfrastructureState): string {
  const template: any = {
    AWSTemplateFormatVersion: "2010-09-09",
    Description: "Auto-generated by React2AWS IDE",
    Resources: {}
  };

  Object.values(state.resources).forEach(res => {
    const logicalId = res.id.replace(/[^a-zA-Z0-9]/g, ''); // CFN requires alphanumeric IDs
    
    if (res.type === 'VPC') {
      template.Resources[logicalId] = {
        Type: "AWS::EC2::VPC",
        Properties: {
          CidrBlock: (res as any).cidrBlock || "10.0.0.0/16",
          EnableDnsSupport: true,
          EnableDnsHostnames: true
        }
      };
    } 
    else if (res.type === 'RDS') {
      template.Resources[logicalId] = {
        Type: "AWS::RDS::DBInstance",
        Properties: {
          Engine: (res as any).engine || "postgres",
          DBInstanceClass: "db.t3.micro",
          AllocatedStorage: (res as any).storageGb ? (res as any).storageGb.toString() : "20"
        }
      };
    }
    else if (res.type === 'S3') {
      template.Resources[logicalId] = {
        Type: "AWS::S3::Bucket",
        Properties: {
          AccessControl: "Private"
        }
      };
    }
  });

  return JSON.stringify(template, null, 2);
}